baseURL = 'https://docs.fsq.ai'
languageCode = 'en-us'
title = 'Fuzzy Sequence'

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"

contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGitInfo = false

[[menu.main]]
  name = "About"
  post = '<sup><i class="fa-solid fa-up-right-from-square" aria-hidden="true"></i></sup>'
  weight = 10
  url = "https://fsq.ai"

[[menu.main]]
  name = "API"
  post = '<sup><i class="fa-solid fa-up-right-from-square" aria-hidden="true"></i></sup>'
  weight = 20
  url = "https://buf.build/fuzzy-sequence/fsq"
