baseURL = 'https://docs.fsq.ai'
languageCode = 'en-us'
title = 'Fuzzy Sequence'

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"

contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGitInfo = false

[[menu.main]]
  name = "About"
  weight = 10
  url = "https://fsq.ai"
