baseURL = 'https://docs.fsq.ai'
languageCode = 'en-us'
title = 'Fuzzy Sequence'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"

[[menu.main]]
name = "Home"
weight = 10
url = "https://fsq.ai"
